"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['checkers.py']
APP_NAME = "Checkers"
DATA_FILES = [
    ("images", ["images/*.png"])
]
OPTIONS = {
    "argv_emulation": True
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', "pygame"],
)